version: "3.8"

services:
  coffee-ai:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./ai_models:/app/ai_models # Mount local models directory
    restart: unless-stopped
